spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      default_schema: roky_bank
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: postgresql
  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/roky_bank
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: df159357