server:
  port: 8090
spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        default_schema: roky_bank
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://loandb:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: df159357